### ISSUE TITLE
Removing two hardcoded strings

### ISSUE THREAD

**Issue by cage2** [libre-man/unix-opts#28]
Hi!

I noticed there are two hardcoded string in the code (in `describe` function):
- "usage"
  https://github.com/libre-man/unix-opts/blob/master/unix-opts.lisp#L579

- "Available options"
  https://github.com/libre-man/unix-opts/blob/master/unix-opts.lisp#L584

These two do not work fine in a program that is internationalized (that is a pity for me because i found this library awesome); i wonder if would be a good idea to add two more key arguments for `describe` function that default to these two hardcoded values?

I am thinking something like:

```lisp 
(defun describe (&key ... (usage-of-label "usage") (available-options-label "Available options") ...
```
If you agree that the problem actually exists and with the proposed solution (and of course i am OK for suggestions!) i happily  would send a PR (it is an easy task i guess ;-) ).

Bye!
C.

**Comment by libre-man** [comment]
Hi @cage2,

That seems like an awesome idea, it would be more than open to a PR to implement this.
