### ISSUE TITLE
Maintaining unix-opts

### ISSUE THREAD

**Issue by libre-man** [libre-man/unix-opts#8]
Hi I would be interested in maintaining `unix-opts`. I use the project for an internal app and do kind of know how the internals work. I would be interested in maintaining the project as is, but hopefully also expand it to have a bit more options.

**Comment by mrkkrp** [comment]
You need to delete your copy of the repo though because I get the error message "libre-man/unix-opts already exists" when I try to start the ownership transfer.

**Comment by libre-man** [comment]
Done!

**Comment by vindarel** [comment]
Hello, it doesn't seem the change is done here, is it ?

Next we'll have to ask to change metada on QL.

**Comment by mrkkrp** [comment]
Actually it looks like I'm still the owner. @libre-man, are you still interested in taking over the library?

**Comment by libre-man** [comment]
Yes!

**Comment by mrkkrp** [comment]
Well you should click something somwhere then, because the status is still "the repository is being transferred to libre-man". You should have received something about this.

**Comment by libre-man** [comment]
Oh sorry I completely missed that request, and now I'm getting "Oops! That repository transfer has expired.". Maybe you can try again?

**Comment by mrkkrp** [comment]
Retried.

**Comment by libre-man** [comment]
Ok it works now, thanks!
