### ISSUE TITLE
Unbound variable: CCL::COMMAND-LINE-ARGUMENTS on CCL

### ISSUE THREAD

**Issue by iBelieve** [libre-man/unix-opts#9]
I'm using CCL 1.11.5. When using unix-opts, I get the following error: `Unbound variable: CCL::COMMAND-LINE-ARGUMENTS on CCL`. Looking at the code, it appears that both `#+:ccl` and `#+clozure` are being triggered, resulting in the wrong variable being used. According to [the docs](https://ccl.clozure.com/docs/ccl.html#operating-system-interface), `*command-line-argument-list*` is the correct variable to use.

Here's the contents of `*features*` with both `:ccl` and `:clozure`:

> (:QUICKLISP :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :ASDF-UNICODE :PRIMARY-CLASSES :COMMON-LISP :OPENMCL :CCL :CCL-1.2 :CCL-1.3 :CCL-1.4 :CCL-1.5 :CCL-1.6 :CCL-1.7 :CCL-1.8 :CCL-1.9 :CCL-1.10 :CCL-1.11 :CLOZURE :CLOZURE-COMMON-LISP :ANSI-CL :UNIX :OPENMCL-UNICODE-STRINGS :IPV6 :OPENMCL-NATIVE-THREADS :OPENMCL-PARTIAL-MOP :MCL-COMMON-MOP-SUBSET :OPENMCL-MOP-2 :OPENMCL-PRIVATE-HASH-TABLES :STATIC-CONSES-SHOULD-WORK-WITH-EGC-IN-CCL :X86-64 :X86_64 :X86-TARGET :X86-HOST :X8664-TARGET :X8664-HOST :LINUX-HOST :LINUX-TARGET :LINUXX86-TARGET :LINUXX8664-TARGET :LINUXX8664-HOST :64-BIT-TARGET :64-BIT-HOST :LINUX :LITTLE-ENDIAN-TARGET :LITTLE-ENDIAN-HOST)

**Comment by libre-man** [comment]
Hi thanks for the report!

I was able to reproduce the error locally so I will fix it asap and add clozure to the CI system.
